# Plugins
Plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "+Con"
email: "masconmdz@gmail.com"
description: "Evento para unirse al desarrollo de la comunidad Argentina."
baseurl: "/argentina2018"
url: "https://mas-con.github.io/"
permalink: "/blog/:title"
# googleAnalyticsTrackingId: "UA-43643469-5"
# googleAnalyticsSiteUrl: "gdg-x.github.io"
# siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Los seres humanos que disfrutan de la tecnología"
organizerAlternateName: "Los seres humanos que disfrutan de la tecnología"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "masconferencia@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://mas-con.github.io/"

# Head
metaKeywords: "event, mascon, mendoza, programacion, programming, design, argentina, "
twitterAccount: "@masconmdz"
# socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
# c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "mailto:masconmdz@gmail.com"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Programación"}
 - {permalink: "/speakers/", text: "Oradores"}
 - {permalink: "/team/", text: "Los organizadores"}

# bottomNavigationLinks:
#  - {link: "#", text: "Become a speaker"}
# rightNavigationButtons:
#  - {link: "#", text: "Become a speaker"}

# Hero Block
heroImage: "black.png"
heroTitle: "+Con | <typeout> "
eventDate: "20 Octubre - UTN Mendoza"
typeoutTextValues: '"", "ferencia", "versación ", "vos ", "Diseno" ,"desarrollo"'
typeoutFallback: "Season"
# heroButtons:
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
#  - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "Conocé +Con"
aboutBlock:
 - {title: "Talks", image: "bigdata.jpg", text: "Charlas sobre lenguajes de programación, frameworks y más." }
 - {title: "Lightning Talks", image: "iot.png", text: "Lightning Talks, charlas más intensas sobre desarrollo." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "180", specialCharacter: "+", info: "participantes", detail: ""}
 - {count: "7", specialCharacter: "+", info: "horas", detail: "charlas y contenido"}
 - {count: "15", specialCharacter: "+", info: "grandes", detail: "oradores"}
 - {count: "1", specialCharacter: "", info: "día", detail: "puro aprendizaje"}

# Latest News Block
latestNewsTitle: ""

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Oradores"
rockstarSpeakersButtonText: "Ver todos los oradores"

# Location Block
locationBlockTitle: "UTN Mendoza"
eventLocationName: ""
eventLocationLink: "#"
eventStreetAddress: "Coronel, J. Rodriguez 273"
eventAddressLocality: "Mendoza"
eventAddressLocalityRegion: "Mendoza"
eventPostalCode: "5500"
eventAddressCountry: "Argentina"
eventStartTime: "2018-10-20T10:00"
eventDoorTime: "09:00"
eventEndTime: "2018-10-20T18:00"
eventPlaceCoordinates: "-32.897141846900354,-68.8533890247345"
mapCenterCoordinates: "-32.897141846900354,-68.8533890247345"
mapMobileCenterCoordinates: "-32.897141846900354,-68.8533890247345"

# Venue Block
venueBlockTitle: "UTN - Mendoza"
venueBigImage: "auditorio.jpg"
venueSmallImage1: "entrada.jpg"
venueSmallImage2: "novaamerica-2.jpg"

#venueSmallImage3: "venue_3.jpg"
venueTitle: "Auditorio"
venueFeatures: ["Buen ambiente para las conversaciones. "," Una buena acústica, aire acondicionado."]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: ""
twitterHashTag: "masconmdz"
twitterFeed: ""

# Partners Block
organizersTitle: ""
# partnersTitle: "Para ser patrocinador, por favor, póngase en contacto con nosotros por correo electrónico masconmdz@gmail.com"
partnersC4sponsorsButton: "Para ser patrocinador, por favor, póngase en contacto con nosotros por correo electrónico masconmdz@gmail.com"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Mantenete al día con las noticias!"
# subscribeAction: "#"


# Footer
socialLinks:
 - {link: "https://twitter.com/masconmdz", icon: "twitter"}
 - {link: "https://www.facebook.com/masconmdz/", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://mas-con.github.io", text: "+Con Conference"}
   - {link: "https://github.com/mas-con/code-conduct-mas-con", text: "Code of Conduct"}

 -
  title: "Contactos"
  links:

   - {link: "mailto:masconmdz@gmail.com", text: "masconmdz@gmail.com"}
